# Generated by Django 5.0.7 on 2024-07-10 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PayApp', '0002_transactiondata_delete_paymentresponse'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transactiondata',
            name='bank_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='transactiondata',
            name='bank_transaction_id',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
